// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tsw.EventBus.Outbox;

#nullable disable

namespace Tsw.EventBus.Outbox.Migrations
{
    [DbContext(typeof(IntegrationEventLogContext))]
    partial class IntegrationEventLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventState", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("EventStates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "NotPublished"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "InProgress"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Published"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "PublishedFailed"
                        });
                });

            modelBuilder.Entity("Tsw.EventBus.Outbox.IntegrationEventLog", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("State")
                        .HasColumnType("smallint");

                    b.Property<int>("TimesSent")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.ToTable("IntegrationEventLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
