name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
    paths:
      - 'EventBus/EventBus.Common/**'
jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
            
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Package
        run: >
          echo 'github.ref_name=${{ github.ref_name }}'
          dotnet pack --no-restore --no-build --configuration Release 
          -p:PackageVersion=${{ github.ref_name }} --output .
        
      - name: Publish
        run: >
          dotnet nuget push Tsw.${{ github.ref_name }}.nupkg 
          --source https://nuget.pkg.github.com/TrotsenkoSergey/index.json 
          --api-key ${{ secrets.NUGET_API_KEY }}
